version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admyn287
      POSTGRES_PASSWORD: Hosp$287!2%
      POSTGRES_DB: dbalmacenes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: